### ISSUE TITLE
Feature request hostname change

### ISSUE THREAD

**Issue by XpamAmAdEuS** [ronnyvdbr/RaspberryIPCamera#1]
HI.
Can u please add option to set hostname.

**Comment by gabe817** [comment]
@XpamAmAdEuS  - It seems you were able to get this router running.  I installed the v1.4 image referred to in the document. I wasn't able to login using admin & raspberry as suggested in the document but I was able to login with root & raspberry.  However, now I'm sitting at the terminal prompt without a clue as to how to open the web gui so that I can input the router settings.  The router is running because I can pick it up when I do a WiFi scan from my mobile device.  I just can't connect because I don't know the password and don't know how to get to the router settings to set one up.
