### ISSUE TITLE
Raspberry Zero Wifi custom build

### ISSUE THREAD

**Issue by fgrandval** [ronnyvdbr/RaspberryIPCamera#10]
Hi Ronny,
I'm trying to install it on Raspberry Zero, but as you know there's no ethernet port or wifi.
I've a wifi dongle, but how to build a custom image of RaspberryIPCamera with my own wifi credentials ?
Thanks!

**Comment by ronnyvdbr** [comment]
You will need to edit 2 files:
1. edit /etc/network/interfaces, set it to below config:
auto lo
iface lo inet loopback
iface eth0 inet manual
allow-hotplug wlan0
iface wlan0 inet manual
wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

2. edit /etc/wpa_supplicant/wpa_supplicant.conf to include your wifi network details
country=GB
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
network={
ssid="My Wifi Network"
proto=RSN
key_mgmt=WPA-PSK
pairwise=CCMP
group=CCMP
psk="MyWifiPassword"
}

save and reboot your raspberry pi.

**Comment by szewc83** [comment]
I have tried installing using the installation.sh as a step-by-step on a Pi Zero W. 
I have finished the whole code literally typing every line one by one and ended up with three Failures at boot: 
Failed to start/load random seed.
Failed to start the PHP Fast CGI Process Manager (See 'systemctl status php5-fpm.service for details)
Failed to start A high performance web server and a reverse proxy server. (See 'systemctl status nginx.service' for details)

Question is whether I made a mistake (i.e. type-o) somewhere down the line or this will just not run on Pi Zero? I have to admit that I did make a couple mistakes on the way but thought I corrected them since I could progress to the end...

Any clues? :) 
Thanks
